### ISSUE TITLE
New born monsters after death do not attack back.

### ISSUE THREAD

**Issue by bahamus20** [JoeAlisson/L2jOrg#123] opened 2020-04-17 14:32 UTC
New born monsters after death do not attack back to player.

(I test with monster level 5-8)

**Comment by JoeAlisson** [comment] 2020-04-17 15:30
Any specific monster or area ? I couldn't reproduce it

**Comment by bahamus20** [comment] 2020-04-17 16:09
I think all monster

**Comment by bahamus20** [comment] 2020-04-17 16:19
same problem with all monster (tested)

**Comment by vicochips** [comment] 2020-04-17 17:36
I can't reproduce the bug :(

**Comment by bahamus20** [comment] 2020-04-18 02:25
Try this (I don't know if there will be any side effects.)
Index: Gameserver/src/main/org.l2j.gameserver/org/l2j/gameserver/model/actor/Attackable.java
===================================================================
--- Gameserver/src/main/org.l2j.gameserver/org/l2j/gameserver/model/actor/Attackable.java	(revision 1326)
+++ Gameserver/src/main/org.l2j.gameserver/org/l2j/gameserver/model/actor/Attackable.java	(working copy)
@@ -1176,10 +1176,18 @@
         _seederObjId = 0;
 
         // check the region where this mob is, do not activate the AI if region is inactive.
-         if (hasAI() && !isInActiveRegion()) {
-            getAI().stopAITask();
+        // if (hasAI() && !isInActiveRegion()) {
+        // getAI().stopAITask();
+        // Set the intention of the Attackable to AI_INTENTION_ACTIVE
+        getAI().setIntention(CtrlIntention.AI_INTENTION_ACTIVE);
+        		
+       // Check the region where this mob is, do not activate the AI if region is inactive.
+        	if (!isInActiveRegion())
+        	{
+        		getAI().stopAITask();
+        	}
          }
-    }
+    
 
     @Override
     public void onRespawn() {

**Comment by bahamus20** [comment] 2020-04-18 02:28
[Attackable.zip](https://github.com/JoeAlisson/L2jOrg/files/4495892/Attackable.zip)

**Comment by JoeAlisson** [comment] 2020-04-18 11:51
Hi @bahamus20  I think is already fixed on c1ee5e3,  can you test it ?

**Closed** 2020-04-19 06:07 UTC
Labels: bug
